---
swagger: "2.0"
info:
  version: "1.0"
  title: "lambda-authorizer-app"
host: "2j6bylkx5b.execute-api.eu-north-1.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /users/{username}:
    get:
      parameters:
      - name: "username"
        in: "path"
        required: true
        type: "string"
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      responses: {}
      security:
      - LambdaAuthorizer: []
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:eu-north-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-north-1:590183762752:function:lambda-authorizer-app-GetUserByUsernameFunction-PCUYOtZwSWGc/invocations"
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
securityDefinitions:
  LambdaAuthorizer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerUri: "arn:aws:apigateway:eu-north-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-north-1:590183762752:function:lambda-authorizer-app-LambdaAuthorizerFunction-UkKZkfpwdJEc/invocations"
      authorizerResultTtlInSeconds: 300
      type: "token"
x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false
